//THIS FILE SHOULD BE EXECUTE AS PSQL SUPER USER

CREATE USER admin WITH PASSWORD 'admin';
CREATE DATABASE walle;
GRANT ALL PRIVILEGES ON DATABASE walle TO admin;
GRANT ALL ON SCHEMA public TO admin;
